<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="1" disabled="0" errors="0" timestamp="2016-03-17T11:34:00" time="0" name="AllTests">
  <testsuite name="falseTest" tests="1" failures="1" disabled="0" errors="0" time="0">
    <testcase name="Negative" status="run" time="0" classname="falseTest">
      <failure message="common/lib/ScannedDoc/unit_test_gt/scanned_doc_ut_gt.cpp:38&#x0A;Value of: 1&#x0A;  Actual: true&#x0A;Expected: false" type=""><![CDATA[common/lib/ScannedDoc/unit_test_gt/scanned_doc_ut_gt.cpp:38
Value of: 1
  Actual: true
Expected: false]]></failure>
      <failure message="common/lib/ScannedDoc/unit_test_gt/scanned_doc_ut_gt.cpp:39&#x0A;Value of: 0&#x0A;  Actual: false&#x0A;Expected: true" type=""><![CDATA[common/lib/ScannedDoc/unit_test_gt/scanned_doc_ut_gt.cpp:39
Value of: 0
  Actual: false
Expected: true]]></failure>
    </testcase>
  </testsuite>
</testsuites>
